version: 1.2.{build}

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.2.5
  - choco install maven --version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0
  - choco install stylecop --version 4.7

environment:
  sonar.stylecop.msBuildPath: C:\PROGRA~2\MSBuild\12.0\Bin\MSBuild.exe
  sonar.stylecop.styleCopDllPath: C:\PROGRA~2\STYLEC~1.7\StyleCop.dll

  matrix:
  - RUN_ITS: false
  - RUN_ITS: true
    SQ_VERSION: LTS
  - RUN_ITS: true
    SQ_VERSION: LATEST_RELEASE
  - RUN_ITS: true
    SQ_VERSION: DEV

matrix:
  fast_finish: true

build_script:
  - ps: ./appveyor.ps1

test: off
